// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // Netlify FunctionsはサーバーレスのためCLI(migrate/db seed)はSupabaseの
    // 直接接続(DIRECT_URL)を使う。アプリ実行時の接続はsrc/lib/prisma.tsで
    // DATABASE_URL(Transaction Pooler)を直接参照している。
    url: process.env["DIRECT_URL"],
  },
});
